name: npmjs.com publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: git config --global user.name "github-actions"
      - run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: yarn install --frozen-lockfile
      - run: yarn release -y
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          GH_TOKEN: ${{secrets.gh_token}}
